server:
  applicationConnectors:
  - type: http 
    port: 8280
  adminConnectors:
  - type: http
    port: 8281

logging:

  level: WARN

  # Logger-specific levels.
  loggers:

    # Set specific levels
    "com.sun.jersey.api.client": DEBUG
    "io.dropwizard": DEBUG
    "it.siletto": DEBUG

### application context
appContext:
  /rest/*

### signing keys
privateKeyFile:
  D:/dev/workspaces/personale/arthropods.eu/private/oauth-bridge/src/main/resources/private.key
publicKeyFile:
  D:/dev/workspaces/personale/arthropods.eu/private/oauth-bridge/src/main/resources/public.key

### proxy ###
#proxyHost:
#  localhost
#proxyPort:
#  3110

### mongodb species ###
mongodb.species.hostname:
  localhost
mongodb.species.database:
  arthropods_species
mongodb.species.port:
  27017

### mongodb site ###
mongodb.site.hostname:
  localhost
mongodb.site.database:
  arthropods_site
mongodb.site.port:
  27017
  